### ISSUE TITLE
gap-open and gap-extend not taking effect

### ISSUE THREAD

**Issue by davidbuterez** [soedinglab/MMseqs2#201]
## Expected Behavior
Be able to specify the parameters gap open and extend costs
## Current Behavior
Not able to use the two options

## Steps to Reproduce (for bugs)
I have 2 very simple test files, a.fasta and b.fasta: [a.txt](https://github.com/soedinglab/MMseqs2/files/3166780/a.txt), [b.txt](https://github.com/soedinglab/MMseqs2/files/3166779/b.txt) (here attached as txt)

I run this command for each file:
`mmseqs.bat createdb <fastafile> <dbname> --dbtype 2 --max-seq-len 38 `

Then `search` as follows:
`mmseqs.bat search aDB bDB alignDB tmp --search-type 3 -k 3 -s 7.5  -e INF --min-ungapped-score 0 -a --gap-open N --gap-extend M `
(integers in place of N, M)

The output is in [searchout.txt](https://github.com/soedinglab/MMseqs2/files/3166806/searchout.txt)

I then run `convertalis` to summarize:
`mmseqs convertalis aDB bDB alignDB alnRes.txt --search-type 3  --format-output "qseq,tseq,query,target,raw,bits,qaln,taln"`

Output: [convout.txt](https://github.com/soedinglab/MMseqs2/files/3166817/convout.txt)
Note that in the `convertalis `output, the values for gap open and extension are:
```
Gap open cost           11
Gap extension cost      1
```

Is this a bug in the output or is it not taking the settings into account? I have tried many combinations of settings and the reported scores are always to same.

## MMseqs Output (for bugs)
Output is included above for each command

## Context
I am trying to get alignment scores for short DNA sequences. Gaps are important as I am looking for scores which are not heavily influenced by gaps and mismatches in general (little penalty).

## Your Environment
09 May 2019, Windows version from https://mmseqs.com/latest/
Windows 10.0.17763 Build 17763
No issues running MMseqs2, other than errors such as 
```
posix_madvise returned an error alignDB
posix_madvise returned an error tmp/3046893737278326904/aln
posix_madvise returned an error tmp/3046893737278326904/search/pref_0
```
when running `search `and `convertalis`

**Comment by martin-steinegger** [comment]
@davidbuterez the convertalis module needs gap-open and gap-extend only to compute the raw score from the bit score. So if you use `--format-output raw`

**Comment by davidbuterez** [comment]
@martin-steinegger I am sorry but I'm still confused, do I need to pass additional options or am I doing something wrong?

**Comment by martin-steinegger** [comment]
@davidbuterez I check your search log and the alignment steps used the gap open and extend parameters. So the alignment should be computerd with gap open 3 and gap extend 0 (see `searchout.txt`). I am not sure if -e inf actually works, I never used this.

     align ... \    --gap-open 3 --gap-extend 0 ...

However the computation of the raw score in convertalis uses the gap open 11 and gap extend 1 to recompute the raw score from the bit score.  

     mmseqs convertalis aDB bDB alignDB alnRes.txt --search-type 3 --format-output "qseq,tseq,query,target,raw,bits,qaln,taln"  --gap-open 3 --gap-extend 0 

Just a warning. You use two quite experimental features of mmseqs2, (1) Windows and (2) nucleotide searches.

**Comment by davidbuterez** [comment]
@martin-steinegger Thanks for the answer!
Intuitively, I've already tried running your latest suggested command:
`mmseqs convertalis aDB bDB alignDB alnRes.txt --search-type 3 --format-output "qseq,tseq,query,target,raw,bits,qaln,taln"  --gap-open 3 --gap-extend 0`

However, no output file is generated (in this case, `alnRes.txt`) when the gap options are passed to convertalis.

As for the warning, I am quickly testing things on my PC, but the usually I will run this for bigger datasets on a Linux machine. I will test on Linux as well to see if there is any difference.

**Comment by martin-steinegger** [comment]
I have fixed an issues with gap open and extend in nucl/nucl searches. However gap open and gap extend need to be greater 1.

**Comment by davidbuterez** [comment]
@martin-steinegger Thanks, I appreciate how quickly this was solved!
Just a quick question, with options such as `--gap-open 3 --gap-extend 2`, I am getting negative scores. What does this mean? I don't think that it's mentioned in the documentation. Since these are lower than the defaults shouldn't the scores be higher (and negatives is a first)?

**Comment by martin-steinegger** [comment]
Where do you see the negative scores? I could not reproduce them. 
My output for your example is 

    a0      b0      13
    a0      b0      5

**Comment by davidbuterez** [comment]
I tried different sequences, for example:
a.fasta:
```
>a0
CTTGGTGAGGCGCTTGCCGC
```
b.fasta
```
>b0
CGATTCAAATGGTCTCAAAC
```
The output I get is:
`a0	b0	-36`

**Comment by martin-steinegger** [comment]
I still get a positive score.

    mmseqs search a b aln2 tmp2 --search-type 3 -k 3 -s 7.5 -e INF --min-ungapped-score 0 -a --gap-open 3 --gap-extend 2
    mmseqs convertalis a b aln2 aln2.tsv  --format-output "query,target,raw" --gap-open 3 --gap-extend 2 --search-type 3

aln2.tsv

    a0       b0      5

**Comment by davidbuterez** [comment]
@martin-steinegger I can confirm that on Windows I get the same result you.
However, on Linux I get -36 and convertalis takes a suspiciously long time:

```
mmseqs convertalis a b aln2 aln2.tsv  --format-output "query,target,raw" --gap-open 3 --gap-extend 2 --search-type 3
convertalis a b aln2 aln2.tsv --format-output query,target,raw --gap-open 3 --gap-extend 2 --search-type 3 

MMseqs Version:        	0e3fbac011481fd6291b92a0b48adce98fc0f007
Substitution matrix    	blosum62.out
Alignment format       	0
Format alignment output	query,target,raw
Translation table      	1
Gap open cost          	3
Gap extension cost     	2
Database output        	false
Preload mode           	0
Search type            	3
Threads                	12
Compressed             	0
Verbosity              	3

[=================================================================] 100.00% 0.01  eta -
Time for merging files: 0h 0m 0s 0ms
Time for processing: 0h 0m 36s 386ms
```

**Comment by martin-steinegger** [comment]
interesting. I assume that ALP does not converges, this library estimates the parameter of the Gumbel distribution. I tried your example on linux as well and could not reproduce the issues.

**Comment by davidbuterez** [comment]
Thanks, I've reinstalled the latest version and it seems to work as expected, I am not seeing negative scores anymore.
