### ISSUE TITLE
Sequence entry is dropped from cluster after mmseqs clusterupdate workflow

### ISSUE THREAD

**Issue by jianye00** [soedinglab/MMseqs2#961]
Hi, I am using your example sequence data included in mmseq release to demonstrate this issue.  Please tell me what we need to do to update a cluster db correctly.  We were using it to update our cluster database and it's crucial that the updating does not miss sequences. 

I have tested two versions including the latest version:
bin/mmseqs version
b804fbe384e6f6c9fe96322ec0e92d48bccd0a42

I constructed clusters exactly following mmseqs command line example (i.e., I first cluster an old sequence db and then update the resulting cluster db using a new sequence db.  I see the updated cluster db missed sequence entries that are still present in new sequence db).

Here are the commands I used:

bin/mmseqs createdb <(head -n 10000 examples/DB.fasta) sequenceDB
bin/mmseqs cluster sequenceDB clusterDB tmp
bin/mmseqs createdb <(tail -n +1001 examples/DB.fasta | head -n 15000) updateSequenceDB
mmseqs clusterupdate sequenceDB updateSequenceDB clusterDB newSequenceDB newClusterDB tmp
bin/mmseqs createtsv newSequenceDB newSequenceDB newClusterDB newClusterDB.tsv

So newClusterDB is the updated cluster db.  You can see it only contains only 7313 sequence entries (i.e., cluster members) while the new sequence db contains 7500 sequences.

 wc newClusterDB.tsv
  7313  14626 123022 newClusterDB.tsv

wc updateSequenceDB.lookup
  7500  22500 114486 updateSequenceDB.lookup
wc newSequenceDB.lookup
  7500  22500 115124 newSequenceDB.lookup

Here is one example sequence ( X7SER2 ) that the newClusterDB db missed:
It is in the updateSequenceDB that is used to update the cluster db:

grep  X7SER2 updateSequenceDB.lookup
5962    X7SER2  0

It is also in the new sequence db after cluster update:

grep  X7SER2 newSequenceDB.lookup
2152    X7SER2  0

Yet it is missing in the resulting cluster db:
grep X7SER2 newClusterDB.tsv

**Comment by milot-mirdita** [comment]
This should be fixed in the latest commit. We were removing deleted cluster members and deleted representatives, however in the latter case not recovering members of deleted representatives. Now these can be assigned to an existing cluster or form new clusters.

**Comment by milot-mirdita** [comment]
You can download precompiled binaries at https://mmseqs.com/latest or at https://mmseqs.com/archive/eaecacf4ba24e9c8a0f2a1da115603ebc80710ad for specific commits. Or alternatively compiles from source.

**Comment by jianye00** [comment]
Thank you so much. We'll try it.

**Comment by jianye00** [comment]
Hi,
I tried mmseqs-linux-avx2.tar.gz from https://mmseqs.com/latest but it still have the same problem as I initially reported.  Is the fix somehow not getting into the latest release?  Thanks.

**Comment by milot-mirdita** [comment]
The issue should be fixed.

What does `mmseqs version` report?

Did you execute the same commands as above again and have the same issue?

**Comment by jianye00** [comment]
Yes I used exact commands as above that I used originally. Here is the version output:

bin/mmseqs 
MMseqs2 (Many against Many sequence searching) is an open-source software suite for very fast, 
parallelized protein sequence searches and clustering of huge protein sequence data sets.

Please cite: M. Steinegger and J. Soding. MMseqs2 enables sensitive protein sequence searching for the analysis of massive data sets. Nature Biotechnology, doi:10.1038/nbt.3988 (2017).

MMseqs2 Version: 18d8ddc2f468b8a00cec9addb3d2328eb790ac9e
Â© Martin Steinegger (martin.steinegger@snu.ac.kr)

**Comment by jianye00** [comment]
I am sorry I just realized I used wrong version of mmseq (our installed previous version) in the  clusterupdate step...your latest version did fix the problem.  I apologize for the confusion.  Thank you.

**Comment by martin-steinegger** [comment]
Thank you for the feedback!
